Repository honeycombio/honeyaws, pull requests merged in 2021-11, with the labels that each got.

#166 Bump libhoney-go
  go.mod
  go.sum
Labels: version: bump patch, type: maintenance

#167 Bump go version to 1.17
  .circleci/config.yml
  go.mod
Labels: version: bump patch, type: maintenance

#168 Prepare v1.4.2 release
  CHANGELOG.md
  RELEASE.md
Labels: type: maintenance, version: no bump

#173 Update dependabot.yml
  .github/dependabot.yml
Labels: type: maintenance, version: no bump, merge at will
