Repository honeycombio/honeyaws, pull requests merged in 2022-11, with the labels that each got.

#219 bump honeytail from 1.8.1 to 1.8.2
  go.mod
  go.sum
Labels: type: maintenance, version: no bump, merge at will

#220 prepare 1.4.5 release
  CHANGELOG.md
Labels: no-changelog

#221 maint: update docker orb version
  .circleci/config.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#222 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#223 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump

#224 maint: transfer to api team
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/add-to-project-v2.yml
Labels: no-changelog
